# ----------------------- #
#      Main Configs       #
# ----------------------- #

url:                https://quantumhack.ml
title:              Quantum Hack
email:              mail@quantumhack.ml
author:             Quantum Hack
description:        We are an interdisciplinary team with both academic and technical backgrounds, mainly interested in exploiting quantum information machinery for decentralizing data through blockchain technologies. We aim to further improve areas where optimization problems play an important role and research new blockchain structures and mining schemes with quantum advantages. 
copyright:          '2020 Quantum Hack'
credits:            ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

include:
  - .htaccess
  - _pages

sass:
  sass_dir:         _sass


# Build settings
markdown:           kramdown
highlighter:        rouge
permalink:          pretty
lsi:                false
excerpt_separator:  "\n\n"
incremental:        false



# Markdown Processing
kramdown:
  input:            GFM
  hard_wrap:        false
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  smart_quotes:     lsquo,rsquo,ldquo,rdquo
  enable_coderay:   false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins:
  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-seo-tag
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title:          twitter
    url:            https://twitter.com/QuantumhackM
  - title:          github
    url:            https://github.com/quantumhack
  - title:          linkedin
    url:            https://www.linkedin.com/in/quantumhack-ml-a1b2081a3
