# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://quantumhack.ml
title: Quantum Hack
email: mail@quantumhack.ml
author: Quantum Hack
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: '2020 Quantum Hack'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/QilpO
  - title: github
    url: https://github.com/quantumhack/
  - title: linkedin
    url:
